---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Add postgres key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add postgres repo
  apt_repository:
    state: present
    repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    filename: postgresql

- name: Install postgres
  apt:
    name: postgresql-{{ postgres_version }}
    state: present


- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes