---
- include_tasks: clone_repogit.yml
- include_tasks: prepare.yml
- include_tasks: install_postgres.yml
- include_tasks: create_db.yml
- include_tasks: install_redis.yml
- include_tasks: execute_app.yml
- include_tasks: start_service.yml