---
# service syste
- name: Create visit service
  template:
    src: myapp.service.j2
    dest: /etc/systemd/system/visit.service

- name: Reload systemd
  systemd_service:
    daemon_reload: true

- name: Start myapp
  systemd_service:
    name: visit.service
    state: started
    enabled: true
